apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-httpd
spec:
  type: NodePort
  ports:
    - port: 3050 
      targetPort: 80
      nodePort: 31000  
  selector:
    app: apache_webserver  